# -*- coding: utf-8 -*-
"""HF_ChatBoT_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14owhJxZJMh-ZMr2C_0vNO7xrUJkbHAz7
"""

!pip install transformers torch accelerate

!pip install --upgrade huggingface_hub
# Alternatively, to ensure CLI tools are included
!pip install -U "huggingface_hub[cli]"

"""## Consolidate Chatbot Implementations

### Subtask:
Review existing `chatbot` functions and `get_llama_response` methods. Consolidate them into a single, clean, and modular implementation, removing any redundant or duplicated code.

"""

from transformers import AutoTokenizer, pipeline
import torch
from huggingface_hub import login

# Log in to Hugging Face to access gated models
# Make sure to create a Hugging Face token in your settings (https://huggingface.co/settings/tokens)
# and set it as a Colab secret named 'HF_TOKEN'.
login()

model_name = "meta-llama/Llama-2-7b-chat-hf" # meta-llama/Llama-2-7b-hf

tokenizer = AutoTokenizer.from_pretrained(model_name, token=True)

llama_pipeline = pipeline(
    "text-generation",  # LLM task
    model=model_name,
    torch_dtype=torch.float16,
    device_map="auto",
)

def chatbot(tokenizer_obj, llama_pipeline_obj):
    messages = [
        {"role": "system", "content": "You are a helpful assistant."}
    ]

    while True:
        user_input = input("User: ")

        if user_input.lower() in ["quit", "bye", "exit"]:
            print("Goodbye...")
            break

        # Append user message to the conversation history
        messages.append({"role": "user", "content": user_input})

        # Get response from the Llama model by passing the full conversation history
        response_text = get_llama_response(messages, tokenizer_obj, llama_pipeline_obj)

        # Print the bot's response (which should be a string)
        print("Bot:", response_text)

        # Append the assistant's string response to the conversation history
        messages.append({"role": "assistant", "content": response_text})


def get_llama_response(current_messages: list, tokenizer_obj, llama_pipeline_obj) -> str:
    """
    Generate a response from the Llama model.

    Parameters:
        current_messages (list): The list of conversation messages for the model.
        tokenizer_obj: The tokenizer object.
        llama_pipeline_obj: The Llama pipeline object.

    Returns:
        str: The model's generated response.
    """
    # Apply chat template to the messages to get a single string prompt
    formatted_prompt = tokenizer_obj.apply_chat_template(current_messages, tokenize=False, add_generation_prompt=True)

    sequences = llama_pipeline_obj(
        formatted_prompt, # Pass the formatted string prompt
        do_sample=True,
        top_k=10,
        num_return_sequences=1,
        eos_token_id=tokenizer_obj.eos_token_id,
        max_new_tokens=1024, # Changed from max_length to max_new_tokens
        pad_token_id=tokenizer_obj.eos_token_id # Added pad_token_id to avoid warning
    )
    full_generated_text = sequences[0]['generated_text']

    # The pipeline returns the entire conversation including the input prompt.
    # We need to extract only the last assistant's reply.
    # For Llama-2 chat models, the assistant's response typically follows '[/INST]'.
    last_inst_idx = full_generated_text.rfind('[/INST]')

    if last_inst_idx != -1:
        # Extract the text after the last '[/INST]'
        assistant_response = full_generated_text[last_inst_idx + len('[/INST]'):].strip()

        # Remove any trailing '</s>' token if present
        if assistant_response.endswith(tokenizer_obj.eos_token):
            assistant_response = assistant_response[:-len(tokenizer_obj.eos_token)].strip()

        # If the model over-generates and starts a new turn, truncate it.
        new_turn_start_idx = assistant_response.find('<s>[INST]')
        if new_turn_start_idx != -1:
            assistant_response = assistant_response[:new_turn_start_idx].strip()

        return assistant_response
    else:
        # Fallback if '[/INST]' is not found (should not happen with Llama-2 chat models)
        return full_generated_text


if __name__ == "__main__":
    print("Start chatting with the bot (type 'quit' to stop)!")
    # Pass the globally defined tokenizer and llama_pipeline objects to the chatbot function
    chatbot(tokenizer, llama_pipeline)

"""# Task
**Increase max_length in get_llama_response and re-run consolidated chatbot code**: Modify the `get_llama_response` function in cell `b003f91d` to set `max_length` to a higher value (e.g., 1024) to allow for longer generated responses. Then, execute the consolidated code in cell `b003f91d` to apply the fix and test the chatbot functionality with extended conversation history.

## Increase max_length in get_llama_response

### Subtask:
Modify the `get_llama_response` function in cell `b003f91d` to set `max_length` to a higher value (e.g., 1024) to allow for longer generated responses.

## Re-run consolidated chatbot code

### Subtask:
Execute the consolidated code in cell `b003f91d` to apply the fix and test the chatbot functionality with extended conversation history.

## Summary:

### Data Analysis Key Findings
*   The `max_length` parameter in the `get_llama_response` function, which was intended to be increased to 1024, was already set to this value prior to the execution of this task.

### Insights or Next Steps
*   Ensure that pre-existing code states are verified before attempting modifications to avoid redundant actions.
"""