# -*- coding: utf-8 -*-
"""HF_ChatBoT_FINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vSmqEUEObIgAcSxowhfmxDW1Ty3mD5FB
"""

!pip install transformers torch accelerate

!pip install --upgrade huggingface_hub
# Alternatively, to ensure CLI tools are included
#!pip install -U "huggingface_hub[cli]"

!huggingface-cli login
!huggingface-cli whoami

"""Loading Model & Tokenizer
Here, we are preparing our session by loading both the Llama model and its associated tokenizer.

The tokenizer will help in converting our text prompts into a format that the model can understand and process.
"""

from transformers import AutoTokenizer
import transformers
import torch
from huggingface_hub import login

# Log in to Hugging Face to access gated models
login()

model = "meta-llama/Llama-2-7b-chat-hf" # meta-llama/Llama-2-7b-hf

tokenizer = AutoTokenizer.from_pretrained(model, token=True)

"""Creating the Llama Pipeline
We'll set up a pipeline for text generation.

This pipeline simplifies the process of feeding prompts to our model and receiving generated text as output.

Note: This cell takes 2-3 minutes to run
"""

from transformers import pipeline

llama_pipeline = pipeline(
    "text-generation",  # LLM task
    model=model,
    torch_dtype=torch.float16,
    device_map="auto",
)

"""#Getting Responses
With everything set up, let's see how Llama responds to some sample queries.
"""

def get_llama_response(prompt: str) -> None:
    """
    Generate a response from the Llama model.

    Parameters:
        prompt (str): The user's input/question for the model.

    Returns:
        None: Prints the model's response.
    """
    sequences = llama_pipeline(
        prompt,
        do_sample=True,
        top_k=10,
        num_return_sequences=1,
        eos_token_id=tokenizer.eos_token_id,
        max_length=256,
    )
    #print("Chatbot:", sequences[0]['generated_text'])
    return sequences[0]['generated_text']



prompt = 'I liked "Breaking Bad" and "Band of Brothers". Do you have any recommendations of other shows I might like?\n'
#get_llama_response(prompt)

def chatbot():
    messages = [
        {"role": "system", "content": "You are a helpful assistant."}
    ]

    while True:
        user_input = input("User: ")

        if user_input.lower() in ["quit", "bye", "exit"]:
            print("Goodbye...")
            break

        messages.append({"role": "user", "content": user_input})

        response = get_llama_response(messages)

        print("Bot:", response)

        messages.append({"role": "assistant", "content": response})


if __name__ == "__main__":
    print("Start chatting with the bot (type 'quit' to stop)!")
    chatbot()

from huggingface_hub import InferenceClient

client = InferenceClient()

def get_llama_response(messages):
    response = client.chat.completions.create(
        model="meta-llama/Meta-Llama-3-8B-Instruct",
        messages=messages,
        max_tokens=256
    )
    return response.choices[0].message.content


def chatbot():
    messages = [
        {"role": "system", "content": "You are a helpful assistant."}
    ]

    while True:
        user_input = input("User: ")

        if user_input.lower() in ["quit", "bye", "exit"]:
            print("Goodbye...")
            break

        messages.append({"role": "user", "content": user_input})

        response = get_llama_response(messages)

        print("Bot:", response)

        messages.append({"role": "assistant", "content": response})


if __name__ == "__main__":
    print("Start chatting with the bot (type 'quit' to stop)!")
    chatbot()

def main():
    print("Start chatting with the bot (type 'quit' to stop)!")
    chatbot()

